### ISSUE TITLE
cannot use Destroyable because destruction was requested

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake-ros#102]
In testing for https://github.com/RobotLocomotion/drake-ros/issues/99#issuecomment-1203181987, I suspended my laptop, then resumed it. I then disconnected from WiFi, then reconnected. I was hoping this would cause the warning about "lo" not supporting multicast to reappear.

However, when I did so, I now get the following stack trace:
```
$ bazel-bin/external/ros2/ros2 node list
Traceback (most recent call last):
  File "{bazel-bin}/external/ros2/archive/bin/ros2", line 33, in <module>
    sys.exit(load_entry_point('ros2cli==0.18.3', 'console_scripts', 'ros2')())
  File "{runfiles}/ros2/archive/lib/python3.8/site-packages/ros2cli/cli.py", line 89, in main
    rc = extension.main(parser=parser, args=args)
  File "{runfiles}/ros2/archive/lib/python3.8/site-packages/ros2node/command/node.py", line 37, in main
    return extension.main(args=args)
  File "{runfiles}/ros2/archive/lib/python3.8/site-packages/ros2node/verb/list.py", line 38, in main
    node_names = get_node_names(node=node, include_hidden_nodes=args.all)
  File "{runfiles}/ros2/archive/lib/python3.8/site-packages/ros2node/api/__init__.py", line 60, in get_node_names
    node_names_and_namespaces = node.get_node_names_and_namespaces()
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1169, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1341, in parse_response
    return u.close()
  File "/usr/lib/python3.8/xmlrpc/client.py", line 655, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: "<class 'rclpy._rclpy_pybind11.InvalidHandle'>:cannot use Destroyable because destruction was requested">
``` 

Unclear what state there is in the system.

@sloretz Sorry for the barrage, but any ideas? \cc @IanTheEngineer 
(I will try to restart my system)

**Comment by EricCousineau-TRI** [comment]
Also, feel free to ignore this for the next couple of weeks.
